//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComparisonClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IComparisonService")]
    public interface IComparisonService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComparisonService/Compare", ReplyAction="http://tempuri.org/IComparisonService/CompareResponse")]
        double Compare(double n1, double n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComparisonService/Compare", ReplyAction="http://tempuri.org/IComparisonService/CompareResponse")]
        System.Threading.Tasks.Task<double> CompareAsync(double n1, double n2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IComparisonServiceChannel : ComparisonClient.ServiceReference1.IComparisonService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ComparisonServiceClient : System.ServiceModel.ClientBase<ComparisonClient.ServiceReference1.IComparisonService>, ComparisonClient.ServiceReference1.IComparisonService {
        
        public ComparisonServiceClient() {
        }
        
        public ComparisonServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ComparisonServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComparisonServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComparisonServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double Compare(double n1, double n2) {
            return base.Channel.Compare(n1, n2);
        }
        
        public System.Threading.Tasks.Task<double> CompareAsync(double n1, double n2) {
            return base.Channel.CompareAsync(n1, n2);
        }
    }
}
